# Generated by Django 2.2.6 on 2019-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historialm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.TextField()),
                ('fecha_inicio', models.IntegerField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
