# Generated by Django 2.2.6 on 2019-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
