# Generated by Django 2.2.6 on 2019-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vacuna', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
