# Generated by Django 2.2.6 on 2019-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('notas', models.TextField()),
                ('clinica', models.CharField(max_length=20)),
                ('horario', models.DateField()),
            ],
        ),
    ]
